// @generated by scripts/generate_roblox_fflags.luau -- do not edit by hand.
//
// Luau fast flags as the Roblox client 0.740.0.7400927 sets them, limited to the
// flags Luau 0.740 declares. Regenerate when either one moves.

pub(crate) const ROBLOX_FFLAGS: &[(&str, bool)] = &[
    ("DebugCodegenOptSize", true),
    ("LuauAllowGlobalDeclarationToBeCalledClass", true),
    ("LuauCallFeedback", true),
    ("LuauCallLuauTm", true),
    ("LuauCodegenNoLinearFastpcall", true),
    ("LuauCodegenNopPadding", true),
    ("LuauCodegenPropagateFallbackTags", false),
    ("LuauCompileCleanBlockDeadClose", true),
    ("LuauCompileConcatTargetTop", true),
    ("LuauCompileIifeInline", true),
    ("LuauCompileLoopUnrollZero", true),
    ("LuauCompileMoveElision", true),
    ("LuauCompileUndoEmitAdjust", true),
    ("LuauCostModel", true),
    ("LuauEasyStateInit", true),
    ("LuauEmitCallFeedback", true),
    ("LuauEnumMoreEdges", true),
    ("LuauFastpcall", true),
    ("LuauFastpcallInterrupt", true),
    ("LuauNewPointerEncode", true),
    ("LuauNoDuplicateBinaryPrefix", true),
    ("LuauPcallOptimize", true),
    ("LuauPrettyPrintVisualizeIndexerAccess", true),
    ("LuauSelfIsSelfAndAlwaysSelf", true),
    ("LuauSingleTypeOptionalPackReturnsAttributeParens", true),
    ("LuauSplitTableLookups", true),
    ("LuauTableArrayAdjustCheck", true),
    ("LuauTableArrayShrinkOrder", true),
    ("LuauTableMoveTimeoutFix", true),
    ("LuauVirtualBcBuilder", true),
];
