[package]
name = "lune-std-fs"
version = "0.3.5"
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/XopoIII/LuneBlox"
description = "Lune standard library - FS"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
mlua = { version = "0.12.2", features = ["luau"] }

async-fs = "2.2"
bstr = "1.13"
futures-lite = "2.6"

lune-utils = { version = "0.3.5", path = "../lune-utils" }
lune-std-datetime = { version = "0.3.5", path = "../lune-std-datetime" }
